/**
 * /terms — Página pública de Términos y Condiciones.
 *
 * Carga el contenido HTML desde el backend vía el BFF route handler
 * `/api/legal/terms` (server-side). Si el backend falla o devuelve contenido
 * vacío, muestra el contenido fallback hardcodeado.
 *
 * El mismo contenido está disponible en el TermsModal para uso inline.
 */

import Link from 'next/link';
import { FileText, ArrowLeft } from 'lucide-react';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Términos y Condiciones — Delta Salud' };

interface TermsData {
  contentHtml: string;
  version: string;
  updatedAt: string;
}

async function fetchTerms(): Promise<TermsData> {
  const BACKEND_URL = process.env.BACKEND_INTERNAL_URL ?? 'http://localhost:3001';
  try {
    const r = await fetch(`${BACKEND_URL}/api/legal/terms`, { cache: 'no-store' });
    const json = (await r.json()) as {
      success?: boolean;
      data?: Partial<TermsData>;
    };
    if (!r.ok || !json?.success || !json.data) {
      return { contentHtml: '', version: '', updatedAt: '' };
    }
    return {
      contentHtml: json.data.contentHtml ?? '',
      version: json.data.version ?? '',
      updatedAt: json.data.updatedAt ?? '',
    };
  } catch {
    return { contentHtml: '', version: '', updatedAt: '' };
  }
}

function formatDate(rawDate: string): string {
  if (!rawDate) return 'Abril 2026';
  try {
    return new Intl.DateTimeFormat('es-VE', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    }).format(new Date(rawDate));
  } catch {
    return rawDate;
  }
}

export default async function TermsPage() {
  const terms = await fetchTerms();
  const hasRealContent = terms.contentHtml.trim().length > 0;
  const displayDate = formatDate(terms.updatedAt);

  return (
    <div className="min-h-screen bg-slate-50 py-16 px-6">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-teal-600 mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Volver al inicio
        </Link>

        <div className="bg-white rounded-2xl border border-slate-200 p-8 sm:p-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-teal-100 rounded-xl flex items-center justify-center">
              <FileText className="w-6 h-6 text-teal-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">Términos y Condiciones</h1>
              <p className="text-sm text-slate-500 mt-0.5">Última actualización: {displayDate}</p>
            </div>
          </div>

          {hasRealContent ? (
            <div
              className="terms-page-content text-slate-700 text-sm leading-relaxed"
              /* contentHtml is TRUSTED content generated by our own admins */
              dangerouslySetInnerHTML={{ __html: terms.contentHtml }}
            />
          ) : (
            /* Fallback hardcodeado mientras el backend no tenga contenido */
            <div className="prose prose-slate max-w-none space-y-4 text-slate-700">
              <p>Al usar Delta Salud aceptas estos términos. Léelos con atención.</p>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">1. Servicio</h2>
                <p>
                  Delta Salud provee una plataforma SaaS para que profesionales de la salud
                  gestionen su práctica médica privada en Venezuela. El servicio incluye agenda,
                  historia clínica electrónica, cobros, CRM y portal del paciente.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">2. Período de prueba</h2>
                <p>
                  Durante el período de prueba el acceso es gratuito por 1 año. El servicio se
                  ofrece &ldquo;tal cual&rdquo; sin garantías expresas. Reservamos el derecho de
                  modificar funcionalidades.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">
                  3. Responsabilidad médica
                </h2>
                <p>
                  Delta Salud es una herramienta de gestión administrativa. Las decisiones clínicas,
                  diagnósticos, tratamientos y prescripciones son responsabilidad exclusiva del
                  profesional médico que usa la plataforma.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">4. Uso aceptable</h2>
                <p>
                  El especialista se compromete a usar la plataforma sólo para su práctica legítima.
                  Está prohibido cargar información falsa, suplantar identidad o usar la plataforma
                  para fines ilegales.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">
                  5. Suspensión de cuenta
                </h2>
                <p>
                  Nos reservamos el derecho de suspender cuentas que violen estos términos, sin
                  previo aviso.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-slate-900 mt-6">6. Jurisdicción</h2>
                <p>
                  Estos términos se rigen por las leyes de la República Bolivariana de Venezuela.
                </p>
              </section>

              <p className="text-sm text-slate-500 mt-8 pt-6 border-t border-slate-200">
                Para preguntas sobre estos términos:{' '}
                <a href="mailto:hola@deltahealth.tech" className="text-teal-600 hover:underline">
                  hola@deltahealth.tech
                </a>
              </p>
            </div>
          )}

          {terms.version && (
            <p className="text-xs text-slate-400 mt-8 pt-4 border-t border-slate-100">
              Versión:{' '}
              <span className="font-mono bg-slate-50 px-1.5 py-0.5 rounded border border-slate-100">
                {terms.version}
              </span>
            </p>
          )}
        </div>
      </div>

      <style>{`
        .terms-page-content h1 { font-size: 1.25rem; font-weight: 700; color: #1E293B; margin-top: 1.5rem; margin-bottom: 0.5rem; }
        .terms-page-content h2 { font-size: 1.125rem; font-weight: 600; color: #1E293B; margin-top: 1.5rem; margin-bottom: 0.5rem; }
        .terms-page-content h3 { font-size: 1rem; font-weight: 600; color: #334155; margin-top: 1.25rem; margin-bottom: 0.25rem; }
        .terms-page-content p { margin-bottom: 0.875rem; }
        .terms-page-content ul, .terms-page-content ol { padding-left: 1.5rem; margin-bottom: 0.875rem; }
        .terms-page-content li { margin-bottom: 0.375rem; }
        .terms-page-content a { color: #0D9488; text-decoration: underline; }
        .terms-page-content strong { font-weight: 600; }
        .terms-page-content section { margin-bottom: 0.5rem; }
      `}</style>
    </div>
  );
}
