/**
 * ISellerRepository — domain contract for seller-related persistence.
 *
 * All methods operate on the `profiles` table. Sellers are regular profile
 * rows with role = 'seller'. The two new columns they own are:
 *   - seller_code  — the short alphanumeric code the seller shares publicly.
 *   - sold_by      — FK on the specialist's profile pointing at the seller.
 *
 * No PII is accepted as input for logging. Implementations must never log
 * fullName, email, cedula, phone, or any patient-level field.
 */

export const SELLER_REPOSITORY = Symbol('ISellerRepository');

// ---------------------------------------------------------------------------
// Value objects / read models
// ---------------------------------------------------------------------------

/** Minimal seller profile returned to callers. No contact PII beyond fullName. */
export interface SellerProfile {
  id: string;
  /** PII — full name. Seller portal context only. Do NOT log. */
  fullName: string;
  sellerCode: string;
  createdAt: Date;
}

/** Specialist row as seen from the seller portal — identity + subscription snapshot. */
export interface SellerSpecialistRow {
  id: string;
  /** PII — full name. Seller portal context only. Do NOT log. */
  fullName: string;
  specialty: string | null;
  plan: string | null;
  subscriptionStatus: string | null;
  createdAt: Date;
  /** Null when the specialist has never logged in. */
  lastSignInAt: Date | null;
}

// ---------------------------------------------------------------------------
// Input shapes
// ---------------------------------------------------------------------------

export interface CreateSellerParams {
  id: string;
  fullName: string;
  email: string;
  /** Generated by the use case — never comes from the client. */
  sellerCode: string;
}

export interface CreateSoldSpecialistParams {
  id: string;
  fullName: string;
  email: string;
  specialty?: string | null;
  cedula?: string | null;
  phone?: string | null;
  /** Always 'free_trial'. Sellers cannot assign paid plans. */
  plan: 'free_trial';
  /** Profile id of the authenticated seller — from session, never from request body. */
  soldBy: string;
}

// ---------------------------------------------------------------------------
// Repository interface
// ---------------------------------------------------------------------------

export interface ISellerRepository {
  /**
   * Creates a new seller profile (role = 'seller') with the given seller_code.
   * Throws DoctorEmailConflictError (409) when the email is already registered.
   */
  createSeller(params: CreateSellerParams): Promise<SellerProfile>;

  /**
   * Returns the seller profile for the given id, or null when not found.
   * Used by GET /api/seller/me so a seller can read their own code.
   */
  findById(id: string): Promise<SellerProfile | null>;

  /**
   * Returns the seller profile whose seller_code matches the given code, or
   * null when no match is found. Used for code validation and onboarding linking.
   */
  findByCode(code: string): Promise<SellerProfile | null>;

  /**
   * Checks whether a given seller_code string is already taken.
   * Used during code generation to retry on collision.
   */
  codeExists(code: string): Promise<boolean>;

  /**
   * Returns all specialist profiles where sold_by = sellerId.
   * Empty array when the seller has not yet onboarded any specialist.
   */
  listSoldSpecialists(sellerId: string): Promise<SellerSpecialistRow[]>;

  /**
   * Returns a single specialist profile by id, only when that specialist was
   * sold by the given seller. Returns null otherwise (anti-IDOR).
   */
  findSoldSpecialist(sellerId: string, specialistId: string): Promise<SellerSpecialistRow | null>;

  /**
   * Creates a specialist profile + subscription with sold_by = sellerId.
   * Plan is always 'free_trial' — sellers cannot assign paid plans.
   * Throws DoctorEmailConflictError (409) on email collision.
   */
  createSoldSpecialist(params: CreateSoldSpecialistParams): Promise<SellerSpecialistRow>;

  /**
   * Writes sold_by on a specialist profile, but ONLY when it is currently null.
   * If sold_by is already set, this is a no-op — attribution is immutable once
   * established.
   *
   * This one-write guarantee prevents a second seller_code (e.g. submitted on a
   * re-visit to the onboarding wizard) from overwriting the original attribution.
   */
  linkSoldBy(specialistId: string, sellerId: string): Promise<void>;
}
