import { Body, Controller, Get, Param, ParseUUIDPipe, Post, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import { AppAuthGuard } from '../../../../infrastructure/auth/app-auth.guard';
import { RolesGuard } from '../../../../presentation/guards/roles.guard';
import { Roles } from '../../../../presentation/decorators/roles.decorator';
import { ZodValidationPipe } from '../../../../presentation/pipes/zod-validation.pipe';
import {
  CurrentUser,
  type CurrentUserPayload,
} from '../../../../presentation/decorators/current-user.decorator';
import { CreateSellerUseCase } from '../../application/use-cases/create-seller.use-case';
import { ValidateSellerCodeUseCase } from '../../application/use-cases/validate-seller-code.use-case';
import { CreateSellerSpecialistUseCase } from '../../application/use-cases/create-seller-specialist.use-case';
import { ListSellerSpecialistsUseCase } from '../../application/use-cases/list-seller-specialists.use-case';
import { GetSellerSpecialistUseCase } from '../../application/use-cases/get-seller-specialist.use-case';
import { GetSellerProfileUseCase } from '../../application/use-cases/get-seller-profile.use-case';
import type {
  SellerProfile,
  SellerSpecialistRow,
} from '../../domain/repositories/seller.repository';

// ---------------------------------------------------------------------------
// Request body schemas
// ---------------------------------------------------------------------------

/**
 * POST /api/admin/sellers — admin creates a seller account.
 * seller_code is generated by the backend — never accepted from the client.
 */
const CreateSellerBodySchema = z
  .object({
    full_name: z.string().min(2, 'full_name is required').max(300),
    email: z.string().email('email must be a valid email address').max(320),
  })
  .strict();

type CreateSellerBody = z.infer<typeof CreateSellerBodySchema>;

/**
 * POST /api/seller/specialists — seller creates a specialist.
 * plan is always 'free_trial' — sellers cannot assign paid plans.
 */
const CreateSellerSpecialistBodySchema = z
  .object({
    full_name: z.string().min(2, 'full_name is required').max(300),
    email: z.string().email('email must be a valid email address').max(320),
    specialty: z.string().min(1).max(200).nullable().optional(),
    cedula: z.string().max(50).nullable().optional(),
    phone: z.string().max(50).nullable().optional(),
  })
  .strict();

type CreateSellerSpecialistBody = z.infer<typeof CreateSellerSpecialistBodySchema>;

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

interface SuccessResponse<T> {
  success: true;
  data: T;
}

function ok<T>(data: T): SuccessResponse<T> {
  return { success: true, data };
}

function toSellerDto(seller: SellerProfile) {
  return {
    id: seller.id,
    sellerCode: seller.sellerCode,
    createdAt: seller.createdAt,
  };
}

function toSpecialistDto(row: SellerSpecialistRow) {
  return {
    id: row.id,
    specialty: row.specialty,
    plan: row.plan,
    subscriptionStatus: row.subscriptionStatus,
    createdAt: row.createdAt,
    lastSignInAt: row.lastSignInAt,
  };
}

// ---------------------------------------------------------------------------
// Controllers
// ---------------------------------------------------------------------------

/**
 * SellersController — three surfaces:
 *
 *   Admin (super_admin only):
 *     POST /api/admin/sellers         — create a seller account
 *
 *   Seller portal (role=seller only):
 *     GET  /api/seller/me               — my own seller code + display name
 *     GET  /api/seller/specialists      — list specialists I onboarded
 *     GET  /api/seller/specialists/:id  — detail of one specialist
 *     POST /api/seller/specialists      — create a specialist (sold_by from session)
 *
 *   Public (no auth):
 *     GET  /api/public/seller-code/:code — validate a seller code
 *
 * SECURITY:
 *   - Admin endpoint: @Roles('super_admin', 'admin') — el dueño pidió que
 *     CUALQUIER administrador pueda gestionar vendedores, no solo el super.
 *   - Seller endpoints: @Roles('seller').
 *   - sellerId always comes from CurrentUser().sub — never from the request body.
 *   - sold_by is set from the session, never from body.
 *   - NEVER log fullName, email, cedula, phone (PII).
 */
@Controller()
@UseGuards(AppAuthGuard)
export class SellersController {
  constructor(
    private readonly createSeller: CreateSellerUseCase,
    private readonly validateCode: ValidateSellerCodeUseCase,
    private readonly createSpecialist: CreateSellerSpecialistUseCase,
    private readonly listSpecialists: ListSellerSpecialistsUseCase,
    private readonly getSpecialist: GetSellerSpecialistUseCase,
    private readonly getProfile: GetSellerProfileUseCase,
  ) {}

  // ---------------------------------------------------------------------------
  // POST /api/admin/sellers
  // ---------------------------------------------------------------------------

  @Post('admin/sellers')
  @UseGuards(RolesGuard)
  @Roles('super_admin', 'admin')
  async createSellerEndpoint(
    @Body(new ZodValidationPipe(CreateSellerBodySchema)) body: CreateSellerBody,
  ): Promise<SuccessResponse<ReturnType<typeof toSellerDto>>> {
    const seller = await this.createSeller.execute({
      fullName: body.full_name,
      email: body.email,
    });

    return ok(toSellerDto(seller));
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/me
  // ---------------------------------------------------------------------------

  @Get('seller/me')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async getSellerMe(
    @CurrentUser() user: CurrentUserPayload,
  ): Promise<SuccessResponse<{ sellerCode: string; fullName: string }>> {
    const seller = await this.getProfile.execute(user.sub);
    return ok({ sellerCode: seller.sellerCode, fullName: seller.fullName });
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/specialists
  // ---------------------------------------------------------------------------

  @Get('seller/specialists')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async listSpecialistsEndpoint(
    @CurrentUser() user: CurrentUserPayload,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>[]>> {
    const specialists = await this.listSpecialists.execute(user.sub);
    return ok(specialists.map(toSpecialistDto));
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/specialists/:id
  // ---------------------------------------------------------------------------

  @Get('seller/specialists/:id')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async getSpecialistEndpoint(
    @CurrentUser() user: CurrentUserPayload,
    @Param('id', ParseUUIDPipe) specialistId: string,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>>> {
    const specialist = await this.getSpecialist.execute(user.sub, specialistId);
    return ok(toSpecialistDto(specialist));
  }

  // ---------------------------------------------------------------------------
  // POST /api/seller/specialists
  // ---------------------------------------------------------------------------

  @Post('seller/specialists')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async createSpecialistEndpoint(
    @CurrentUser() user: CurrentUserPayload,
    @Body(new ZodValidationPipe(CreateSellerSpecialistBodySchema)) body: CreateSellerSpecialistBody,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>>> {
    const specialist = await this.createSpecialist.execute({
      sellerId: user.sub,
      fullName: body.full_name,
      email: body.email,
      specialty: body.specialty ?? null,
      cedula: body.cedula ?? null,
      phone: body.phone ?? null,
    });

    return ok(toSpecialistDto(specialist));
  }
}

// ---------------------------------------------------------------------------
// Public controller (no auth guard)
// ---------------------------------------------------------------------------

/**
 * SellersPublicController
 *
 * Unauthenticated surface for the seller-code validation endpoint.
 * Used during specialist self-registration before the session exists.
 *
 * GET /api/public/seller-code/:code → { valid, sellerName }
 *
 * SECURITY: only exposes { valid, sellerName } — no id, email, or other field.
 */
@Controller('public')
export class SellersPublicController {
  constructor(private readonly validateCode: ValidateSellerCodeUseCase) {}

  @Get('seller-code/:code')
  async validateSellerCode(
    @Param('code') code: string,
  ): Promise<{ valid: boolean; sellerName: string | null }> {
    return this.validateCode.execute(code);
  }
}
