import { Body, Controller, Get, Param, ParseUUIDPipe, Post, Put, UseGuards } from '@nestjs/common';
import { z } from 'zod';
import { AppAuthGuard } from '../../../../infrastructure/auth/app-auth.guard';
import { RolesGuard } from '../../../../presentation/guards/roles.guard';
import { Roles } from '../../../../presentation/decorators/roles.decorator';
import { ZodValidationPipe } from '../../../../presentation/pipes/zod-validation.pipe';
import {
  CurrentUser,
  type CurrentUserPayload,
} from '../../../../presentation/decorators/current-user.decorator';
import { CreateSellerUseCase } from '../../application/use-cases/create-seller.use-case';
import { ValidateSellerCodeUseCase } from '../../application/use-cases/validate-seller-code.use-case';
import { CreateSellerSpecialistUseCase } from '../../application/use-cases/create-seller-specialist.use-case';
import { ListSellerSpecialistsUseCase } from '../../application/use-cases/list-seller-specialists.use-case';
import { GetSellerSpecialistUseCase } from '../../application/use-cases/get-seller-specialist.use-case';
import { GetSellerProfileUseCase } from '../../application/use-cases/get-seller-profile.use-case';
import { ListSellersUseCase } from '../../application/use-cases/list-sellers.use-case';
import { GetSellerPaymentDetailsUseCase } from '../../application/use-cases/get-seller-payment-details.use-case';
import { UpdateSellerPaymentDetailsUseCase } from '../../application/use-cases/update-seller-payment-details.use-case';
import { GetAdminSellerPaymentDetailsUseCase } from '../../application/use-cases/get-admin-seller-payment-details.use-case';
import { GetSpecialistSellerAssignmentUseCase } from '../../application/use-cases/get-specialist-seller-assignment.use-case';
import { DeactivateSellerAccountUseCase } from '../../application/use-cases/deactivate-seller-account.use-case';
import type {
  SellerProfile,
  SellerAdminRow,
  SellerSpecialistRow,
  SellerPaymentDetails,
} from '../../domain/repositories/seller.repository';

// ---------------------------------------------------------------------------
// Request body schemas
// ---------------------------------------------------------------------------

/**
 * POST /api/admin/sellers — admin creates a seller account.
 * seller_code is generated by the backend — never accepted from the client.
 */
const CreateSellerBodySchema = z
  .object({
    full_name: z.string().min(2, 'full_name is required').max(300),
    email: z.string().email('email must be a valid email address').max(320),
  })
  .strict();

type CreateSellerBody = z.infer<typeof CreateSellerBodySchema>;

/**
 * POST /api/seller/specialists — seller creates a specialist.
 * plan is always 'free_trial' — sellers cannot assign paid plans.
 */
const CreateSellerSpecialistBodySchema = z
  .object({
    full_name: z.string().min(2, 'full_name is required').max(300),
    email: z.string().email('email must be a valid email address').max(320),
    specialty: z.string().min(1).max(200).nullable().optional(),
    cedula: z.string().max(50).nullable().optional(),
    phone: z.string().max(50).nullable().optional(),
  })
  .strict();

type CreateSellerSpecialistBody = z.infer<typeof CreateSellerSpecialistBodySchema>;

/**
 * PUT /api/seller/payment-details
 *
 * The JSONB value is intentionally unstructured: the frontend helpers
 * (`entriesOf` / `withEntries`) manage the shape, and the backend stores it
 * as-is (ADR-044). Zod verifies it is a plain object; the use case validates
 * that entry values are strings and no entry is completely empty.
 *
 * SECURITY: this is financial data — do NOT log the body.
 */
const UpdatePaymentDetailsBodySchema = z
  .object({
    paymentDetails: z.record(z.unknown()),
  })
  .strict();

type UpdatePaymentDetailsBody = z.infer<typeof UpdatePaymentDetailsBodySchema>;

/**
 * POST /api/seller/deactivate — seller deactivates their own account.
 * All fields are optional: the seller can leave a reason or send an empty body.
 */
const DeactivateSellerBodySchema = z
  .object({
    reason: z.string().max(1000).nullable().optional(),
  })
  .strict();

type DeactivateSellerBody = z.infer<typeof DeactivateSellerBodySchema>;

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

interface SuccessResponse<T> {
  success: true;
  data: T;
}

function ok<T>(data: T): SuccessResponse<T> {
  return { success: true, data };
}

function toSellerDto(seller: SellerProfile) {
  return {
    id: seller.id,
    sellerCode: seller.sellerCode,
    createdAt: seller.createdAt,
  };
}

/**
 * Vendedor tal como lo consume `/admin/sellers`.
 *
 * Va en camelCase, igual que el resto de las respuestas de este controller: el
 * BFF lo reenvía tal cual y la pantalla lo lee con estos mismos nombres.
 */
function toSellerAdminDto(row: SellerAdminRow) {
  return {
    id: row.id,
    fullName: row.fullName,
    email: row.email,
    sellerCode: row.sellerCode,
    specialistsCount: row.specialistsCount,
    isActive: row.isActive,
    createdAt: row.createdAt,
    lastSignInAt: row.lastSignInAt,
  };
}

function toPaymentDetailsDto(details: SellerPaymentDetails) {
  return {
    paymentDetails: details.paymentDetails,
  };
}

function toSpecialistDto(row: SellerSpecialistRow) {
  return {
    id: row.id,
    // fullName es la columna principal de la tabla del portal: sin esto el
    // vendedor ve una lista de filas en blanco.
    fullName: row.fullName,
    // Ficha completa (decisión del dueño, 2026-08-17): el vendedor tiene que
    // poder contactar e identificar al especialista que vendió. Nunca se loguea.
    email: row.email,
    phone: row.phone,
    cedula: row.cedula,
    isActive: row.isActive,
    specialty: row.specialty,
    plan: row.plan,
    subscriptionStatus: row.subscriptionStatus,
    createdAt: row.createdAt,
    lastSignInAt: row.lastSignInAt,
    // Distingue "alta incompleta" de "cuenta activa" en el portal del vendedor.
    onboardingCompleted: row.onboardingCompleted,
  };
}

// ---------------------------------------------------------------------------
// Controllers
// ---------------------------------------------------------------------------

/**
 * SellersController — three surfaces:
 *
 *   Admin (super_admin only):
 *     GET  /api/admin/sellers                             — list sellers + specialist counts
 *     POST /api/admin/sellers                             — create a seller account
 *     GET  /api/admin/sellers/:id/payment-details         — view a seller's payment config
 *     GET  /api/admin/specialist-assignment/:specialistId — current seller for a specialist
 *
 *   Seller portal (role=seller only):
 *     GET  /api/seller/me                          — my own seller code + display name
 *     GET  /api/seller/payment-details             — my payment configuration
 *     PUT  /api/seller/payment-details             — update my payment configuration
 *     GET  /api/seller/specialists                 — list specialists I onboarded
 *     GET  /api/seller/specialists/:id             — detail of one specialist
 *     POST /api/seller/specialists                 — create a specialist (sold_by from session)
 *
 *   Public (no auth):
 *     GET  /api/public/seller-code/:code — validate a seller code
 *
 * SECURITY:
 *   - Admin endpoints: @Roles('super_admin').
 *   - Seller endpoints: @Roles('seller').
 *   - sellerId always comes from CurrentUser().sub — never from the request body.
 *   - sold_by is set from the session, never from body.
 *   - Payment details are financial data — NEVER log them.
 *   - NEVER log fullName, email, cedula, phone (PII).
 */
@Controller()
@UseGuards(AppAuthGuard)
export class SellersController {
  constructor(
    private readonly createSeller: CreateSellerUseCase,
    private readonly validateCode: ValidateSellerCodeUseCase,
    private readonly createSpecialist: CreateSellerSpecialistUseCase,
    private readonly listSpecialists: ListSellerSpecialistsUseCase,
    private readonly getSpecialist: GetSellerSpecialistUseCase,
    private readonly getProfile: GetSellerProfileUseCase,
    private readonly listSellers: ListSellersUseCase,
    private readonly getPaymentDetails: GetSellerPaymentDetailsUseCase,
    private readonly updatePaymentDetails: UpdateSellerPaymentDetailsUseCase,
    private readonly getAdminPaymentDetails: GetAdminSellerPaymentDetailsUseCase,
    private readonly getSellerAssignment: GetSpecialistSellerAssignmentUseCase,
    private readonly deactivateAccount: DeactivateSellerAccountUseCase,
  ) {}

  // ---------------------------------------------------------------------------
  // GET /api/admin/sellers
  // ---------------------------------------------------------------------------

  /**
   * Listado de vendedores para la pantalla `/admin/sellers`.
   *
   * Incluye el codigo de cada vendedor y cuantos especialistas dio de alta.
   * Solo super_admin: el rol 'admin' no existe en CurrentUserPayload['role'].
   */
  @Get('admin/sellers')
  @UseGuards(RolesGuard)
  @Roles('super_admin')
  async listSellersEndpoint(): Promise<SuccessResponse<ReturnType<typeof toSellerAdminDto>[]>> {
    const sellers = await this.listSellers.execute();
    return ok(sellers.map(toSellerAdminDto));
  }

  // ---------------------------------------------------------------------------
  // GET /api/admin/sellers/:id/payment-details
  // ---------------------------------------------------------------------------

  /**
   * Returns the payment configuration for a specific seller.
   * Used by the admin panel to know how to pay the seller their commissions.
   *
   * SECURITY: financial data — do NOT log the response body.
   */
  @Get('admin/sellers/:id/payment-details')
  @UseGuards(RolesGuard)
  @Roles('super_admin')
  async getSellerPaymentDetailsAdmin(
    @Param('id', ParseUUIDPipe) sellerId: string,
  ): Promise<SuccessResponse<ReturnType<typeof toPaymentDetailsDto>>> {
    const details = await this.getAdminPaymentDetails.execute(sellerId);
    return ok(toPaymentDetailsDto(details));
  }

  // ---------------------------------------------------------------------------
  // GET /api/admin/specialist-assignment/:specialistId
  // ---------------------------------------------------------------------------

  /**
   * Returns the current seller attribution for a specialist.
   *
   * Used by the assign-seller flow to show a reconfirmation modal when the
   * specialist already has a seller ("moving from X to Y — confirm?").
   *
   * Response always uses the `{ sellerId, sellerName, soldBySource }` shape:
   *   - When the specialist has a seller: all three fields are populated.
   *   - When unattributed or specialist not found: all three fields are null.
   *
   * SECURITY: sellerName is PII — do NOT log the response.
   */
  @Get('admin/specialist-assignment/:specialistId')
  @UseGuards(RolesGuard)
  @Roles('super_admin')
  async getSpecialistAssignment(
    @Param('specialistId', ParseUUIDPipe) specialistId: string,
  ): Promise<
    SuccessResponse<{
      sellerId: string | null;
      sellerName: string | null;
      soldBySource: string | null;
    }>
  > {
    const assignment = await this.getSellerAssignment.execute(specialistId);
    if (!assignment) {
      return ok({ sellerId: null, sellerName: null, soldBySource: null });
    }
    return ok({
      sellerId: assignment.sellerId,
      sellerName: assignment.sellerName,
      soldBySource: assignment.soldBySource,
    });
  }

  // ---------------------------------------------------------------------------
  // POST /api/admin/sellers
  // ---------------------------------------------------------------------------

  @Post('admin/sellers')
  @UseGuards(RolesGuard)
  @Roles('super_admin')
  async createSellerEndpoint(
    @Body(new ZodValidationPipe(CreateSellerBodySchema)) body: CreateSellerBody,
  ): Promise<SuccessResponse<ReturnType<typeof toSellerDto>>> {
    const seller = await this.createSeller.execute({
      fullName: body.full_name,
      email: body.email,
    });

    return ok(toSellerDto(seller));
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/me
  // ---------------------------------------------------------------------------

  @Get('seller/me')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async getSellerMe(
    @CurrentUser() user: CurrentUserPayload,
  ): Promise<SuccessResponse<{ sellerCode: string; fullName: string }>> {
    const seller = await this.getProfile.execute(user.sub);
    return ok({ sellerCode: seller.sellerCode, fullName: seller.fullName });
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/me/payment-details
  // ---------------------------------------------------------------------------

  /**
   * Returns the authenticated seller's payment configuration
   * (how Delta pays their commissions).
   *
   * sellerId comes from the session — never from the request.
   * SECURITY: financial data — do NOT log the response body.
   */
  @Get('seller/payment-details')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async getOwnPaymentDetails(
    @CurrentUser() user: CurrentUserPayload,
  ): Promise<SuccessResponse<ReturnType<typeof toPaymentDetailsDto>>> {
    const details = await this.getPaymentDetails.execute(user.sub);
    return ok(toPaymentDetailsDto(details));
  }

  // ---------------------------------------------------------------------------
  // PUT /api/seller/me/payment-details
  // ---------------------------------------------------------------------------

  /**
   * Updates the authenticated seller's payment configuration.
   *
   * sellerId comes from the session — never from the request body or URL.
   * The payload is the full paymentDetails JSONB value (replace semantics).
   * SECURITY: financial data — do NOT log the request or response body.
   */
  @Put('seller/payment-details')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async updateOwnPaymentDetails(
    @CurrentUser() user: CurrentUserPayload,
    @Body(new ZodValidationPipe(UpdatePaymentDetailsBodySchema)) body: UpdatePaymentDetailsBody,
  ): Promise<SuccessResponse<ReturnType<typeof toPaymentDetailsDto>>> {
    const details = await this.updatePaymentDetails.execute(user.sub, body.paymentDetails);
    return ok(toPaymentDetailsDto(details));
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/specialists
  // ---------------------------------------------------------------------------

  @Get('seller/specialists')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async listSpecialistsEndpoint(
    @CurrentUser() user: CurrentUserPayload,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>[]>> {
    const specialists = await this.listSpecialists.execute(user.sub);
    return ok(specialists.map(toSpecialistDto));
  }

  // ---------------------------------------------------------------------------
  // GET /api/seller/specialists/:id
  // ---------------------------------------------------------------------------

  @Get('seller/specialists/:id')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async getSpecialistEndpoint(
    @CurrentUser() user: CurrentUserPayload,
    @Param('id', ParseUUIDPipe) specialistId: string,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>>> {
    const specialist = await this.getSpecialist.execute(user.sub, specialistId);
    return ok(toSpecialistDto(specialist));
  }

  // ---------------------------------------------------------------------------
  // POST /api/seller/specialists
  // ---------------------------------------------------------------------------

  @Post('seller/specialists')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async createSpecialistEndpoint(
    @CurrentUser() user: CurrentUserPayload,
    @Body(new ZodValidationPipe(CreateSellerSpecialistBodySchema)) body: CreateSellerSpecialistBody,
  ): Promise<SuccessResponse<ReturnType<typeof toSpecialistDto>>> {
    const specialist = await this.createSpecialist.execute({
      sellerId: user.sub,
      fullName: body.full_name,
      email: body.email,
      specialty: body.specialty ?? null,
      cedula: body.cedula ?? null,
      phone: body.phone ?? null,
    });

    return ok(toSpecialistDto(specialist));
  }

  // ---------------------------------------------------------------------------
  // POST /api/seller/deactivate
  // ---------------------------------------------------------------------------

  /**
   * The seller deactivates their own account from the portal.
   *
   * This is always permitted — unlike the specialist flow, no pending items
   * block the exit. The response carries the pending commission summary so the
   * frontend can surface a warning before the seller clicks "Confirmar".
   *
   * sellerId comes from the authenticated session — never from the body.
   * role is verified both by RolesGuard and by the use case (defence in depth).
   *
   * SECURITY: the reason is free text by the account owner and is never logged.
   * The pending amounts are financial data and must never appear in logs.
   *
   * Response shape (exact casing):
   *   { deactivated: true, pendingCommissionsUsd: number, pendingCommissionsCount: number }
   */
  @Post('seller/deactivate')
  @UseGuards(RolesGuard)
  @Roles('seller')
  async deactivateSellerAccount(
    @CurrentUser() user: CurrentUserPayload,
    @Body(new ZodValidationPipe(DeactivateSellerBodySchema)) body: DeactivateSellerBody,
  ): Promise<
    SuccessResponse<{
      deactivated: true;
      pendingCommissionsUsd: number;
      pendingCommissionsCount: number;
    }>
  > {
    const result = await this.deactivateAccount.execute({
      sellerId: user.sub,
      role: user.role,
      reason: body.reason ?? null,
    });

    return ok({
      deactivated: result.deactivated,
      pendingCommissionsUsd: result.pendingCommissionsUsd,
      pendingCommissionsCount: result.pendingCommissionsCount,
    });
  }
}

// ---------------------------------------------------------------------------
// Public controller (no auth guard)
// ---------------------------------------------------------------------------

/** Mismo alfabeto que usa la generación (sin I/L/O/0/1) y largo fijo. */
const SELLER_CODE_FORMAT = /^[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{6}$/;

/**
 * SellersPublicController
 *
 * Unauthenticated surface for the seller-code validation endpoint.
 * Used during specialist self-registration before the session exists.
 *
 * GET /api/public/seller-code/:code → { valid, sellerName }
 *
 * SECURITY: only exposes { valid, sellerName } — no id, email, or other field.
 *
 * ⚠️ SIN RATE LIMITING. El proyecto no tiene throttling en NINGÚN endpoint
 * todavía (ver la nota de Etapa 2 en create-booking.use-case) — no es una
 * carencia de este módulo. Mientras no exista, este endpoint se puede sondear
 * para descubrir códigos activos y el nombre del vendedor. El impacto acotado
 * es que alguien se atribuya un registro a un vendedor ajeno; no expone datos
 * de pacientes. Al agregar throttling al proyecto, ESTE endpoint y el booking
 * público son los dos primeros que lo necesitan.
 */
@Controller('public')
export class SellersPublicController {
  constructor(private readonly validateCode: ValidateSellerCodeUseCase) {}

  /**
   * Responde CON envelope `{ success, data }`, como el resto de los controllers.
   *
   * Devolvía el objeto crudo `{ valid, sellerName }`, y como `backendGet` del BFF
   * desempaqueta `envelope.data`, `result.value` quedaba `undefined` y el BFF
   * respondía SIEMPRE `valid:false`. Resultado: ningún código de vendedor podía
   * validarse nunca, así que la atribución por código estaba muerta y encima el
   * fallo era silencioso (200 + "código inválido", indistinguible de un typo).
   */
  @Get('seller-code/:code')
  async validateSellerCode(
    @Param('code') code: string,
  ): Promise<SuccessResponse<{ valid: boolean; sellerName: string | null }>> {
    // Formato inválido → se responde sin tocar la BD. No frena la enumeración
    // (para eso hace falta throttling) pero evita que basura arbitraria llegue
    // a la base, que es lo único que se puede resolver desde acá.
    if (!SELLER_CODE_FORMAT.test(code)) {
      return ok({ valid: false, sellerName: null });
    }
    return ok(await this.validateCode.execute(code));
  }
}
