// Lista de compañías de seguros de Venezuela (actualizada)
// Incluye HCM, vida, clínica privada, autoseguro y convenios mutualistas comunes.
export const VENEZUELA_INSURANCES = [
  'AIG Uruguay',
  'Banesco Seguros',
  'BBVA Seguros',
  'BHD Seguros',
  'Canarias de Venezuela',
  'Caracas de Liberty Mutual',
  'Caroní, C.A. de Seguros',
  'Constitución Seguros',
  'Caja Metropolitana de Seguros',
  'Estar Seguros',
  'Federal de Seguros',
  'Fidelity Seguros',
  'General de Seguros',
  'Guayana, Seguros',
  'Hispana de Seguros',
  'Horizonte de Seguros',
  'Internacional de Seguros',
  'La Occidental de Seguros',
  'La Previsora',
  'La Regional de Seguros',
  'La Universitaria',
  'La Vitalicia',
  'Latinoamericana de Seguros',
  'Mapfre Venezuela',
  'Mercantil Seguros',
  'Mercantil Salud',
  'MetLife Venezuela',
  'Multinacional de Seguros',
  'Nuevo Mundo Seguros',
  'Ocean Seguros',
  'Oriental de Seguros',
  'Pirámide Seguros',
  'Provincial Seguros',
  'Qualitas Seguros',
  'Rasse Seguros',
  'Seguros Altamira',
  'Seguros Bancentro',
  'Seguros Banesco',
  'Seguros Caracas',
  'Seguros Catatumbo',
  'Seguros Constitución',
  'Seguros Federal',
  'Seguros Horizonte',
  'Seguros La Fe',
  'Seguros La Occidental',
  'Seguros La Previsora',
  'Seguros La Vitalicia',
  'Seguros Latinoamericana',
  'Seguros Los Andes',
  'Seguros Mercantil',
  'Seguros Nuevo Mundo',
  'Seguros Orinoco',
  'Seguros Pirámide',
  'Seguros Provincial',
  'Seguros Qualitas',
  'Seguros Sudamérica',
  'Seguros Universitas',
  'Seguros Uniseguros',
  'Seguros Venezuela',
  'Seguros Zurich Venezuela',
  'Sudamericana de Seguros',
  'Sudamérica',
  'Tele-Ven Seguros',
  'Uniseguros',
  'Universitas de Seguros',
  'Universitas Vida',
  'Venezolana de Seguros y Vida',
  'Vitalicia de Seguros',
  'Zurich Seguros',
  // Auto-administrados / convenios comunes
  'HCM Corporativo — Autogestionado',
  'PDVSA (Convenio)',
  'CANTV (Convenio)',
  'Policlínica Metropolitana — Convenio',
  'CDD Las Mercedes — Convenio',
  'Clínica El Ávila — Convenio',
  'Clínica La Floresta — Convenio',
  'Centro Médico Docente La Trinidad — Convenio',
  'IPASME',
  'IPSFA (Fuerza Armada)',
  'IVSS — Seguro Social',
  // Otros
  'Otro / Personalizado',
].sort((a, b) => a.localeCompare(b, 'es'))
