/**
 * SharedDocumentLink domain entity.
 *
 * Represents a shareable document link generated by a doctor for a specific
 * consultation. The link has a random URL-safe token and can be revoked.
 *
 * Business invariants enforced here:
 *   - canBeRevokedBy() enforces doctor ownership (anti-IDOR).
 *   - isActive() checks status.
 *   - atLeastOneSection() validates that sharing makes sense.
 */
export interface DocumentSections {
  report: boolean;
  prescriptions: boolean;
  ehr: boolean;
}

export interface SharedDocumentLinkCreateParams {
  id: string;
  consultationId: string;
  doctorId: string;
  patientId: string;
  token: string;
  sections: DocumentSections;
  status: 'active' | 'revoked';
  /** Accumulated failed verify-code attempts across ALL codes for this link. */
  failedAttempts: number;
  /** Timestamp of the last time a new code was requested for this link. */
  lastCodeRequestedAt: Date | null;
  createdAt: Date;
}

export class SharedDocumentLink {
  readonly id: string;
  readonly consultationId: string;
  readonly doctorId: string;
  readonly patientId: string;
  readonly token: string;
  readonly sections: DocumentSections;
  readonly status: 'active' | 'revoked';
  /** Accumulated failed verify-code attempts across ALL codes for this link. */
  readonly failedAttempts: number;
  /** Timestamp of the last time a new code was requested for this link. */
  readonly lastCodeRequestedAt: Date | null;
  readonly createdAt: Date;

  /**
   * Maximum total failed attempts allowed across all codes for this link.
   * If the link reaches this threshold, verify-code is blocked even after
   * requesting a new code — the doctor must share a new link.
   */
  static readonly MAX_LINK_FAILED_ATTEMPTS = 10;

  /** Minimum seconds that must elapse between request-code calls. */
  static readonly CODE_REQUEST_COOLDOWN_SECONDS = 60;

  constructor(params: SharedDocumentLinkCreateParams) {
    this.id = params.id;
    this.consultationId = params.consultationId;
    this.doctorId = params.doctorId;
    this.patientId = params.patientId;
    this.token = params.token;
    this.sections = params.sections;
    this.status = params.status;
    this.failedAttempts = params.failedAttempts;
    this.lastCodeRequestedAt = params.lastCodeRequestedAt;
    this.createdAt = params.createdAt;
  }

  /** Returns true when the given doctor owns this link. Anti-IDOR guard. */
  canBeRevokedBy(doctorId: string): boolean {
    return this.doctorId === doctorId;
  }

  /** Returns true when the link is active (not revoked). */
  isActive(): boolean {
    return this.status === 'active';
  }

  /**
   * Returns true when at least one section is selected.
   * A link with no sections selected is meaningless.
   */
  atLeastOneSection(): boolean {
    return this.sections.report || this.sections.prescriptions || this.sections.ehr;
  }

  /**
   * Returns true when the link-level failed-attempt counter has been reached.
   * When true, verify-code is blocked regardless of which code is active.
   * Requesting a new code does NOT reset this counter.
   */
  isLinkBruteforceBlocked(): boolean {
    return this.failedAttempts >= SharedDocumentLink.MAX_LINK_FAILED_ATTEMPTS;
  }

  /**
   * Returns true when a new code was requested too recently.
   * Enforces a 60-second cooldown between request-code calls.
   */
  isCodeRequestOnCooldown(now: Date): boolean {
    if (!this.lastCodeRequestedAt) return false;
    const elapsedMs = now.getTime() - this.lastCodeRequestedAt.getTime();
    return elapsedMs < SharedDocumentLink.CODE_REQUEST_COOLDOWN_SECONDS * 1000;
  }

  static create(params: SharedDocumentLinkCreateParams): SharedDocumentLink {
    return new SharedDocumentLink(params);
  }
}
