import {
  Column,
  CreatedAt,
  DataType,
  Default,
  Model,
  PrimaryKey,
  Table,
  AllowNull,
} from 'sequelize-typescript';

/**
 * Sequelize model for the `shared_document_links` table.
 *
 * Stores the public shareable link metadata. The token is a long random
 * URL-safe string generated by the application (not a UUID) to make
 * enumeration infeasible.
 *
 * No UpdatedAt — links are write-once; revoke is a status change via raw SQL.
 */
@Table({
  tableName: 'shared_document_links',
  timestamps: false,
})
export class SharedDocumentLinkModel extends Model {
  @PrimaryKey
  @Default(DataType.UUIDV4)
  @Column(DataType.UUID)
  declare id: string;

  @Column({ type: DataType.UUID, allowNull: false, field: 'consultation_id' })
  declare consultationId: string;

  @Column({ type: DataType.UUID, allowNull: false, field: 'doctor_id' })
  declare doctorId: string;

  @Column({ type: DataType.UUID, allowNull: false, field: 'patient_id' })
  declare patientId: string;

  /** Long URL-safe random token. UNIQUE per DB constraint. */
  @Column({ type: DataType.TEXT, allowNull: false, unique: true })
  declare token: string;

  /**
   * JSONB: { report: boolean, prescriptions: boolean, ehr: boolean }
   * Determines which document sections are included in the generated PDF.
   */
  @Column({ type: DataType.JSONB, allowNull: false })
  declare sections: Record<string, boolean>;

  @Default('active')
  @Column({ type: DataType.TEXT, allowNull: false })
  declare status: string;

  /**
   * Link-level brute-force counter. Accumulates across all code rotations.
   * Requesting a new code does NOT reset this counter.
   */
  @Default(0)
  @Column({ type: DataType.INTEGER, allowNull: false, field: 'failed_attempts' })
  declare failedAttempts: number;

  /** Timestamp of the last request-code call. Enforces the 60-second cooldown. */
  @AllowNull(true)
  @Column({ type: DataType.DATE, field: 'last_code_requested_at' })
  declare lastCodeRequestedAt: Date | null;

  @CreatedAt
  @Column({ field: 'created_at' })
  declare createdAt: Date;
}
